### ISSUE TITLE
你好，能提供个简单的设计文档嘛？

### ISSUE THREAD

**Issue by liugt34** [ElderJames/shriek-fx#1]
初学DDD，感觉很多地方有点难懂，@ElderJames 能提供一份文档吗？

**Comment by ElderJames** [comment]
感谢支持！由于目前shriek-fx还在开发状态，所以暂时没有文档.只能先看samples，不过还是建议ddd初学者先看原著和《实现领域驱动设计》两本书。

**Comment by ElderJames** [comment]
目前已经有文档，会根据项目完整度来更新
https://elderjames.github.io/shriek-fx
