### ISSUE TITLE
 动态API可以和Swagger集成吗

### ISSUE THREAD

**Issue by XunWind** [ElderJames/shriek-fx#10]
作者 你好 动态生成的API可以和swagger集成吗 还有如果现在已有框架 可以通过引用nuget包的形式 去把框架里面的一些服务层生成动态API吗

**Comment by ElderJames** [comment]
第一个问题，对Swagger的支持是在计划内的，目前还有其他更重要的工作需要完成，比如生成js客户端等等，我相信生成Swagger格式的json也需要一样的基础。
第二个问题，只需要你使用的是ASP.NET Core，那么就可以单独使用动态生成服务端和客户端。请参考文档 https://shriek-projects.github.io/shriek-fx/#/zh-cn/service-simple?id=%E6%9C%8D%E5%8A%A1%E8%B0%83%E7%94%A8

**Comment by ElderJames** [comment]
Swagger已经支持，用法可以参考
https://github.com/Shriek-Projects/shriek-fx/blob/master/samples/Shriek.Samples.WebApiProxy/Program.cs#L61
