### ISSUE TITLE
EventId问题

### ISSUE THREAD

**Issue by likansky** [ElderJames/shriek-fx#12]
public abstract class Event : Message, IEvent
    {
        public abstract string EventId { get; }
        public int Version { get; internal set; }
    }

EventId 要set，否则写库时没有记录

**Comment by ElderJames** [comment]
你好，感谢关注。目前event的反序列化是由json.net负责，数据库存的是具体事件json字符串，反序列化会映射aggregateid，而eventid是读自aggregateid的。

https://github.com/Shriek-Projects/shriek-fx/blob/master/src/Shriek/Storage/DefalutEventStorage.cs
