### ISSUE TITLE
生成有错误

### ISSUE THREAD

**Issue by AnHaoLi** [ElderJames/shriek-fx#14]
具体错误：未能找到元数据文件“D:\Code\shriek-fx-master\samples\Shriek.Samples\bin\Debug\netstandard2.0\Shriek.Samples.dll”	Shriek.Samples.Dapper

环境.：NET Core SDK (3.0.100-preview6-012264)
并在项目根目录增加global.json文件 将现有sdk版本指向2.2
{
  "sdk": {
    "version": "2.2.300"
  }
}

**Comment by AnHaoLi** [comment]
编译通过了，原因没有引用需要的Microsoft.CSharp

**Comment by ElderJames** [comment]
我有空会更新一下.NET Core版本 😄
