### ISSUE TITLE
能不能做一个管道，发送command的一个管道

### ISSUE THREAD

**Issue by quan01994** [ElderJames/shriek-fx#8]
类似 MediatR 的管道，比如有一些的管道中间件，可以验证command的数据合法，还有日志的记录。

**Comment by ElderJames** [comment]
不知道ICommandContext能不能满足你的需求？

**Comment by quan01994** [comment]
感觉有可能跟我的感觉不一样，只是一个建议，
就是你定义一系列管道接口，有Command发送前，有Command发送后，
我去写，继承你的管道接口，有可能会有几个继承发送前的管道接口，
且都加入容器。然后你去取，取得到，就去在Command前发送
当然Event也可以做这么一系列的管道。
这只是一个建议，你感觉这样的功能可以吗？

**Comment by ElderJames** [comment]
这个需求是想解决什么问题？管道一般是在基础设施的通讯组建上用得比较多，当然shriek的command和event是基于消息发布订阅模式的，可以替换习惯组件来实现管道功能
